using System.Numerics;
using Content.Shared._TSF.Surgery;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;

namespace Content.Client._TSF.Surgery;

[GenerateTypedNameReferences]
public sealed partial class SurgeryWindow : FancyWindow
{
    public Action<NetEntity, SurgeryRequestAction>? OnActionRequested;

    public SurgeryWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("tsf-surgery-window-title");
        MinSize = new Vector2(640, 400);
    }

    public void Populate(SurgeryBuiState state)
    {
        LimbList.RemoveAllChildren();
        foreach (var limb in state.Limbs)
        {
            var row = new PanelContainer
            {
                StyleClasses = { "BackgroundPanel" },
                Margin = new Thickness(0, 0, 0, 2)
            };
            var rowInner = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 8,
                Margin = new Thickness(6, 4)
            };

            var label = new Label
            {
                Text = $"{limb.PartName}: {GetConditionText(limb.Condition, limb.FractureStep)}",
                MinWidth = 140,
                VerticalAlignment = Control.VAlignment.Center
            };
            rowInner.AddChild(label);

            if (limb.IsCovered)
            {
                rowInner.AddChild(new Label
                {
                    Text = Loc.GetString("tsf-surgery-limb-covered"),
                    FontColorOverride = Color.Gray,
                    VerticalAlignment = Control.VAlignment.Center
                });
            }
            else
            {
                if (limb.CanReduceDislocation)
                    rowInner.AddChild(MakeActionButton("tsf-surgery-action-reduce-dislocation", limb.PartNetEntity, SurgeryRequestAction.ReduceDislocation));
                if (limb.CanDoIncision)
                    rowInner.AddChild(MakeActionButton("tsf-surgery-action-make-incision", limb.PartNetEntity, SurgeryRequestAction.MakeIncision));
                if (limb.CanDoRetractor)
                    rowInner.AddChild(MakeActionButton("tsf-surgery-action-spread-wound", limb.PartNetEntity, SurgeryRequestAction.SpreadWound));
                if (limb.CanDoGel)
                    rowInner.AddChild(MakeActionButton("tsf-surgery-action-apply-gel", limb.PartNetEntity, SurgeryRequestAction.ApplyBoneGel));
            }

            row.AddChild(rowInner);
            LimbList.AddChild(row);
        }
    }

    private static string GetConditionText(LimbCondition condition, FractureSurgeryStep step)
    {
        return condition switch
        {
            LimbCondition.Ok => Loc.GetString("tsf-surgery-limb-condition-ok"),
            LimbCondition.Dislocated => Loc.GetString("tsf-surgery-limb-condition-dislocated"),
            LimbCondition.Broken => step switch
            {
                FractureSurgeryStep.None => Loc.GetString("tsf-surgery-limb-condition-broken"),
                FractureSurgeryStep.IncisionOpen => Loc.GetString("tsf-surgery-fracture-step-1"),
                FractureSurgeryStep.RetractorSpread => Loc.GetString("tsf-surgery-fracture-step-2"),
                _ => Loc.GetString("tsf-surgery-limb-condition-broken")
            },
            _ => ""
        };
    }

    private Button MakeActionButton(string locId, NetEntity part, SurgeryRequestAction action)
    {
        var btn = new Button
        {
            Text = Loc.GetString(locId),
            StyleClasses = { "OpenRight" }
        };
        btn.OnPressed += _ => OnActionRequested?.Invoke(part, action);
        return btn;
    }
}
