// Copyright (C) 2026 insvrg3ncy
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._TSF.Medical;
using Content.Shared.StationRecords;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._TSF.Medical;

[GenerateTypedNameReferences]
public sealed partial class MedicalRecordsConsoleWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entManager = default!;
    private readonly SpriteSystem _spriteSystem;

    public Action<uint?>? OnKeySelected;
    public Action<StationRecordFilterType, string>? OnFiltersChanged;

    private bool _isPopulating;
    private StationRecordFilterType _currentFilterType;

    public MedicalRecordsConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entManager.System<SpriteSystem>();

        _currentFilterType = StationRecordFilterType.Name;

        foreach (var item in Enum.GetValues<StationRecordFilterType>())
        {
            StationRecordsFilterType.AddItem(GetTypeFilterLocals(item), (int)item);
        }

        RecordListing.OnItemSelected += args =>
        {
            if (_isPopulating || RecordListing[args.ItemIndex].Metadata is not uint cast)
                return;

            OnKeySelected?.Invoke(cast);
        };

        RecordListing.OnItemDeselected += _ =>
        {
            if (!_isPopulating)
                OnKeySelected?.Invoke(null);
        };

        StationRecordsFilterType.OnItemSelected += eventArgs =>
        {
            var type = (StationRecordFilterType)eventArgs.Id;

            if (_currentFilterType != type)
            {
                _currentFilterType = type;
                FilterListingOfRecords();
            }
        };

        StationRecordsFiltersValue.OnTextEntered += args =>
        {
            FilterListingOfRecords(args.Text);
        };

        StationRecordsFilters.OnPressed += _ =>
        {
            FilterListingOfRecords(StationRecordsFiltersValue.Text);
        };

        StationRecordsFiltersReset.OnPressed += _ =>
        {
            StationRecordsFiltersValue.Text = "";
            FilterListingOfRecords();
        };
    }

    public void UpdateState(MedicalRecordsConsoleState state)
    {
        if (state.Filter != null)
        {
            if (state.Filter.Type != _currentFilterType)
                _currentFilterType = state.Filter.Type;

            if (state.Filter.Value != StationRecordsFiltersValue.Text)
                StationRecordsFiltersValue.Text = state.Filter.Value;
        }

        StationRecordsFilterType.SelectId((int)_currentFilterType);

        if (state.RecordListing == null)
        {
            RecordListingStatus.Visible = true;
            RecordListing.Visible = false;
            RecordListingStatus.Text = Loc.GetString("general-station-record-console-empty-state");
            PersonContainer.Visible = false;
            RecordUnselected.Visible = false;
            return;
        }

        RecordListingStatus.Visible = false;
        RecordListing.Visible = true;

        PopulateRecordListing(state.RecordListing, state.SelectedKey);

        var hasSelection = state.SelectedKey != null && state.Record != null;

        RecordUnselected.Visible = !hasSelection;
        PersonContainer.Visible = hasSelection;

        if (!hasSelection || state.Record is not { } rec)
        {
            return;
        }

        var na = Loc.GetString("generic-not-available-shorthand");
        PersonName.Text = rec.Name;
        PersonJob.Text = string.IsNullOrEmpty(rec.JobTitle) ? na : rec.JobTitle;

        if (_prototypeManager.TryIndex<JobIconPrototype>(rec.JobIcon, out var jobIcon))
            PersonJobIcon.Texture = _spriteSystem.Frame0(jobIcon.Icon);
        else
            PersonJobIcon.Texture = _spriteSystem.Frame0(new SpriteSpecifier.Rsi(new ResPath("Interface/Misc/job_icons.rsi"), "Unknown"));

        PersonPrints.Text = rec.Fingerprint ?? na;
        PersonDna.Text = rec.DNA ?? na;

        BodyNotLocatedHint.Visible = state.BodyNotLocated;
        if (state.BodyNotLocated)
            BodyNotLocatedHint.Text = Loc.GetString("tsf-medical-records-console-body-not-located");

        var showEmpty = !state.BodyNotLocated && state.LogLines.Count == 0;
        LogEmptyHint.Visible = showEmpty;
        if (showEmpty)
            LogEmptyHint.Text = Loc.GetString("tsf-medical-records-console-log-empty");

        LogContainer.RemoveAllChildren();
        foreach (var line in state.LogLines)
        {
            LogContainer.AddChild(new Label
            {
                Text = line,
                Margin = new Thickness(0, 0, 0, 2),
            });
        }
    }

    private void PopulateRecordListing(Dictionary<uint, string> listing, uint? selected)
    {
        RecordListing.Clear();
        RecordListing.ClearSelected();

        _isPopulating = true;

        foreach (var (key, name) in listing)
        {
            var item = RecordListing.AddItem(name);
            item.Metadata = key;
            item.Selected = key == selected;
        }

        _isPopulating = false;

        RecordListing.SortItemsByText();
    }

    private void FilterListingOfRecords(string text = "")
    {
        if (!_isPopulating)
            OnFiltersChanged?.Invoke(_currentFilterType, text);
    }

    private string GetTypeFilterLocals(StationRecordFilterType type)
    {
        return Loc.GetString($"general-station-record-{type.ToString().ToLower()}-filter");
    }
}
