name: Сборка и тест Map Renderer

on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ master, staging, stable ]

jobs:
  build:
    name: Сборка Map Renderer
    if: github.actor != 'PJBot' && github.event.pull_request.draft == false
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v4.2.2

      - name: Инициализация субмодулей
        run: |
          git submodule update --init --recursive

      - name: Обновить зависимости движка
        uses: space-wizards/submodule-dependency@v0.1.5

      - name: Обновить субмодули движка
        run: |
          cd RobustToolbox/
          git submodule update --init --recursive

      - name: Установка .NET
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 10.0.x

      - name: Восстановить зависимости
        run: dotnet restore

      - name: Сборка проекта
        run: dotnet build Content.MapRenderer --configuration Release --no-restore /m

      - name: Запуск Map Renderer
        run: dotnet run --project Content.MapRenderer Dev

  ci-success:
    name: CI успешно
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: CI завершён успешно
        run: exit 0
