name: Проверка окончаний строк (CRLF)

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  build:
    name: Проверка CRLF
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Проверить окончания строк
      run: Tools/check_crlf.py
