name: "Метки: На проверке"

on:
  pull_request_target:
    types: [review_requested, opened]

jobs:
  add_label:
    name: Добавить метку
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "S: На проверке"
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: "S: Требуются изменения"
