name: "Метки: Требуются изменения"

on:
  pull_request_review:
    types: [submitted]

jobs:
  update_label:
    name: Обновить метки
    permissions:
      pull-requests: write
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "Status: Требуются изменения"
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: "Status: На проверке"
