name: Проверка конфликтов слияния

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  Label:
    name: Метка конфликта
    if: ( github.event.pull_request.draft == false ) && ( github.actor != 'IanComradeBot' )
    runs-on: ubuntu-latest
    steps:
      - name: Проверить конфликты слияния
        uses: eps1lon/actions-label-merge-conflict@v3.0.0
        with:
          dirtyLabel: "S: Конфликт слияния"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "В этом pull request есть конфликты слияния. Пожалуйста, разрешите их перед проверкой."
