name: "Метки: Ветка stable"

on:
  pull_request_target:
    types:
      - opened
    branches:
      - 'stable'

jobs:
  add_label:
    name: Метка ветки stable
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "Ветка: Стабильная"
