name: "Метки: Одобрено"

on:
  pull_request_review:
    types: [submitted]

jobs:
  remove_label:
    name: Удалить метки
    permissions:
      pull-requests: write
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: |
          Status: На проверке
          Status: Требуются изменения
