name: "Метки: Размер"
on: pull_request_target
jobs:
  size-label:
    name: Метка размера PR
    runs-on: ubuntu-latest
    steps:
      - name: Определить размер
        uses: "pascalgn/size-label-action@v0.5.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          # Настройка порогов размера
          sizes: >
            {
              "0": "XS",
              "10": "S",
              "100": "M",
              "1000": "L",
              "5000": "XL"
            }
