name: Проверка: без обновления субмодуля

on:
  pull_request:
    paths:
      - 'RobustToolbox'

jobs:
  this_aint_right:
    name: Обнаружено изменение субмодуля в PR
    runs-on: ubuntu-latest
    steps:
      - name: Ошибка
        run: exit 1
