name: Сравнение RSI

on:
  pull_request_target:
    paths:
      - '**.rsi/**.png'

jobs:
  diff:
    name: Сравнение изменённых RSI
    runs-on: ubuntu-latest
    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v4.2.2

      - name: Получить изменённые файлы
        id: files
        uses: Ana06/get-changed-files@v2.3.0
        with:
          format: 'space-delimited'
          filter: |
            **.rsi
            **.png

      - name: Сравнить изменённые RSI
        id: diff
        uses: space-wizards/RSIDiffBot@v1.1
        with:
          modified: ${{ steps.files.outputs.modified }}
          removed: ${{ steps.files.outputs.removed }}
          added: ${{ steps.files.outputs.added }}
          basename: ${{ github.event.pull_request.base.repo.full_name }}
          basesha: ${{ github.event.pull_request.base.sha }}
          headname: ${{ github.event.pull_request.head.repo.full_name }}
          headsha: ${{ github.event.pull_request.head.sha }}

      - name: Поиск комментария
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          comment-author: 'github-actions[bot]'
          body-includes: RSI Diff Bot

      - name: Создать комментарий, если не существует
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: |
            ${{ steps.diff.outputs.summary-details }}

      - name: Обновить комментарий, если существует
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            ${{ steps.diff.outputs.summary-details }}

      - name: Добавить пометку об обновлении комментария
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: append
          body: |
            Edit: diff updated after ${{ github.event.pull_request.head.sha }}
