name: YAML-линтер

on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  build:
    name: Проверка YAML
    if: github.actor != 'IanComradeBot' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Инициализация субмодулей
        run: |
          git submodule update --init --recursive
      - name: Обновить зависимости движка
        uses: space-wizards/submodule-dependency@v0.1.5
      - name: Обновить субмодули движка
        run: |
          cd RobustToolbox/
          git submodule update --init --recursive
      - name: Установка .NET
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 10.0.x
      - name: Восстановить зависимости
        run: dotnet restore
      - name: Сборка
        run: dotnet build --configuration Release --no-restore /p:WarningsAsErrors= /m
      - name: Запуск линтера YAML
        run: dotnet run --project Content.YAMLLinter/Content.YAMLLinter.csproj --no-build
